export type AnimationName =
  | 'idle'
  | 'run_forward'
  | 'run_left'
  | 'run_right'
  | 't_pose'
  | 'turn_left_180'
  | 'turn_left_90'
  | 'turn_right_180'
  | 'turn_right_90'
  | 'walk_forward'
  | 'walk_left'
  | 'walk_right'
